### ISSUE TITLE
Oh lawd it's comin

### ISSUE THREAD

**Issue by kcarri** [ethanrusz/rusz.dev#36]
**Describe the bug**
Yes, this is a bug. Quite the monstrosity, if I've ever seen one. And what a bite! Lo, but the bug appeared one day as I was merely perusing the website, as one does. Simply perusing. Admiring the geometric jam that was happening in the corner of my eye while I---BAM! WHIZZ! KABLAM-O! I jerked back in surprise as the heathen overtook me. Yes, I mean the GitHub icon. Why, it supersized before my very eyes, filiing up the page with its undulating pixely quality as it took a moment to restore its own high-resolution. A prank, I did think? But nay! Neigh, even! It did not shrink back to the shadows until I removed my mouse of the very browser from whence it came!

**To Reproduce**
1. Go to the website. Ethan's website. You can't miss it.
2. Do not even click. Scroll warily down the page until you find any of the four icons that imply a link to another page: GitHub, LinkedIn, Email, and SomethingElseThatIForgot.
3. Watch it, dear reader...and beware.

**Expected behavior**
I did not expect anything, famalam. I'm just here straight up vibin' on this dope site, yo.

**Screenshots**
No

**Desktop (please complete the following information):**
 - OS: PC Win10
 - Browser Mozilla Firefox!
 - The newest version! It updated this morning, in fact!

**Additional context**
Ethan is a bully, but a cool bully. Like, the one who will steal your lunch money but then use it to feed stray cats. Hide your pocket change.

**Comment by ethanrusz** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5e03d75a9125d400107f01cb/attachments/5e1780010af39d00106bf593)

**Comment by ethanrusz** [comment]
Fixed in d0480085cd417d1de3e2a922a9f53afb15798b9b.
![fixed](https://user-images.githubusercontent.com/35783974/72099886-9402b780-32ef-11ea-8b47-a8117028ec54.gif)

Thank you @kcarri!
